theme: minima
title: Kavin Mohan's GitHub Pages
author: Kavin Mohan
email: kmohan@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This page is about me and it is for the final AP Comp Sci Project

# social links
instagram_username: kavinm0han # DO NOT include the @ character, or else the build will fail!
github_username:  BlazedFir511 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
